[package]
name = "cryptors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

x25519-dalek = {version = "2.0.0-rc.3", features = ["getrandom","zeroize","static_secrets"]}
hex = "0.4"
