[package]
name = "watch_file"
version = "0.1.0"
edition = "2021"

[dependencies]
notify = { version = "6.1.1", features = ["serde"] }
notify-debouncer-mini = "0.4.1"
# notify = { version = "..", features = [""] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"